import React from 'react';
import { Flame, RotateCcw, AlertTriangle, CheckCircle, Code, Layers, FileCode, Star, GitPullRequest } from 'lucide-react';
import type { AnalysisResult } from '../types';
import { RoastCard } from './RoastCard';
import { HealthScoreGauge } from './HealthScoreGauge';
import { IssueItem } from './IssueItem';
import { SuggestionItem } from './SuggestionItem';
import { CodeInspector } from './CodeInspector';

interface ResultsSectionProps {
  result: AnalysisResult;
  onReset: () => void;
}

export const ResultsSection: React.FC<ResultsSectionProps> = ({ result, onReset }) => {
  return (
    <div className="w-full max-w-5xl mx-auto space-y-8 animate-fadeIn">
      
      {/* Top Banner & Reset CTA */}
      <div className="flex flex-col sm:flex-row items-center justify-between gap-4 pb-2 border-b border-zinc-800">
        <div>
          <h2 className="text-2xl font-bold text-white tracking-tight flex items-center space-x-2">
            <span>Analysis Report</span>
            <span className="text-xs font-mono px-2.5 py-0.5 rounded-full bg-orange-500/10 border border-orange-500/30 text-orange-400">
              Completed
            </span>
          </h2>
          <p className="text-xs text-zinc-400 font-mono mt-0.5">
            Generated by Roast My Project Engine
          </p>
        </div>

        <button
          onClick={onReset}
          className="flex items-center space-x-2 px-4 py-2 rounded-xl bg-zinc-900 hover:bg-zinc-800 border border-zinc-700 text-sm font-medium text-zinc-200 hover:text-white transition shadow-sm cursor-pointer"
        >
          <RotateCcw className="w-4 h-4 text-orange-400" />
          <span>Roast Another Project</span>
        </button>
      </div>

      {/* 1. 🔥 Roast Card (with Re-Roast & Export PNG) */}
      <RoastCard
        roast={result.roast}
        alternativeRoasts={result.alternativeRoasts}
        projectName={result.projectSummary?.projectName}
        intensity={result.intensity}
      />

      {/* 2. Live Code Inspector Tab (if snippets available) */}
      {result.snippets && result.snippets.length > 0 && (
        <CodeInspector snippets={result.snippets} />
      )}

      {/* 3. Grid Layout: Left Column (Health Score + Project Metadata), Right Column (Issues & Suggestions) */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        
        {/* Left Column (4 cols on lg) */}
        <div className="lg:col-span-4 space-y-6">
          
          {/* Health Score Gauge */}
          <HealthScoreGauge
            score={result.score}
            label={result.scoreLabel}
          />

          {/* Project Stats Summary Card */}
          <div className="bg-zinc-900/80 border border-zinc-800 rounded-2xl p-5 space-y-4">
            <div className="text-xs font-mono uppercase tracking-wider text-zinc-400 flex items-center space-x-2">
              <Layers className="w-4 h-4 text-amber-400" />
              <span>Detected Metadata</span>
            </div>

            <div className="space-y-3 text-xs">
              {result.projectSummary?.starsCount !== undefined && (
                <div className="flex items-center justify-between py-1.5 border-b border-zinc-800/80">
                  <span className="text-zinc-400 flex items-center space-x-1.5">
                    <Star className="w-3.5 h-3.5 text-amber-400" />
                    <span>GitHub Stars</span>
                  </span>
                  <span className="font-mono text-zinc-200 font-semibold">
                    {result.projectSummary.starsCount} ⭐
                  </span>
                </div>
              )}

              {result.projectSummary?.openIssuesCount !== undefined && (
                <div className="flex items-center justify-between py-1.5 border-b border-zinc-800/80">
                  <span className="text-zinc-400 flex items-center space-x-1.5">
                    <GitPullRequest className="w-3.5 h-3.5 text-red-400" />
                    <span>Open Issues</span>
                  </span>
                  <span className="font-mono text-zinc-200 font-semibold">
                    {result.projectSummary.openIssuesCount} issues
                  </span>
                </div>
              )}

              <div className="flex items-center justify-between py-1.5 border-b border-zinc-800/80">
                <span className="text-zinc-400 flex items-center space-x-1.5">
                  <FileCode className="w-3.5 h-3.5 text-zinc-500" />
                  <span>Files Count</span>
                </span>
                <span className="font-mono text-zinc-200 font-semibold">
                  {result.projectSummary?.fileCountEstimate ?? 24} files
                </span>
              </div>

              <div className="flex items-center justify-between py-1.5 border-b border-zinc-800/80">
                <span className="text-zinc-400 flex items-center space-x-1.5">
                  <Code className="w-3.5 h-3.5 text-zinc-500" />
                  <span>Code Size</span>
                </span>
                <span className="font-mono text-zinc-200 font-semibold">
                  {result.projectSummary?.linesOfCodeEstimate ?? '~4,000 lines'}
                </span>
              </div>

              {result.projectSummary?.detectedTech && result.projectSummary.detectedTech.length > 0 && (
                <div className="pt-1">
                  <div className="text-[11px] text-zinc-500 mb-2 font-mono">Tech Stack Detected:</div>
                  <div className="flex flex-wrap gap-1.5">
                    {result.projectSummary.detectedTech.map((tech, idx) => (
                      <span
                        key={idx}
                        className="px-2 py-1 rounded bg-zinc-950 border border-zinc-800 text-[10px] font-mono text-orange-400"
                      >
                        {tech}
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </div>
          </div>

        </div>

        {/* Right Column (8 cols on lg) */}
        <div className="lg:col-span-8 space-y-8">
          
          {/* ⚠️ Issues List */}
          <div className="bg-zinc-900/90 border border-zinc-800 rounded-2xl p-6 space-y-4 shadow-lg">
            <div className="flex items-center justify-between">
              <h3 className="text-lg font-bold text-white tracking-tight flex items-center space-x-2">
                <AlertTriangle className="w-5 h-5 text-red-500" />
                <span>Critical Issues Detected ({result.issues.length})</span>
              </h3>
              <span className="text-xs font-mono text-red-400 bg-red-500/10 px-2.5 py-1 rounded-full border border-red-500/20">
                Fix Required
              </span>
            </div>

            <div className="space-y-3">
              {result.issues.map((issue, idx) => (
                <IssueItem key={idx} issue={issue} index={idx} />
              ))}
            </div>
          </div>

          {/* ✅ Suggestions List */}
          <div className="bg-zinc-900/90 border border-zinc-800 rounded-2xl p-6 space-y-4 shadow-lg">
            <div className="flex items-center justify-between">
              <h3 className="text-lg font-bold text-white tracking-tight flex items-center space-x-2">
                <CheckCircle className="w-5 h-5 text-emerald-500" />
                <span>Actionable Recommendations ({result.suggestions.length})</span>
              </h3>
              <span className="text-xs font-mono text-emerald-400 bg-emerald-500/10 px-2.5 py-1 rounded-full border border-emerald-500/20">
                Improvement Plan
              </span>
            </div>

            <div className="space-y-3">
              {result.suggestions.map((suggestion, idx) => (
                <SuggestionItem key={idx} suggestion={suggestion} index={idx} />
              ))}
            </div>
          </div>

        </div>

      </div>

      {/* Bottom CTA Bar */}
      <div className="pt-6 text-center">
        <button
          onClick={onReset}
          className="inline-flex items-center space-x-2 px-8 py-3.5 rounded-xl bg-gradient-to-r from-orange-500 to-red-600 hover:from-orange-600 hover:to-red-700 text-white font-bold text-sm shadow-lg shadow-orange-500/20 transition cursor-pointer"
        >
          <Flame className="w-4 h-4" />
          <span>Analyze Another Project</span>
        </button>
      </div>

    </div>
  );
};
